name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r FileFinder_19/requirements.txt
        pip install flake8  # Install flake8

    - name: Lint with flake8
      run: flake8 .  # Run flake8 for linting

    - name: Check Python Version
      run: python --version

    - name: Check Installed Packages
      run: pip list

    - name: Print Working Directory
      run: pwd

    - name: List Directory Contents
      run: dir

    - name: Verify Scripts Exist
      run: |
        if exist FileFinder_19\file_info_mapfolders.py (echo file_info_mapfolders.py exists) else (echo file_info_mapfolders.py not found)
        if exist FileFinder_19\file_info_version_22.py (echo file_info_version_22.py exists) else (echo file_info_version_22.py not found)
        if exist FileFinder_19\machine_info_migration_centre.py (echo machine_info_migration_centre.py exists) else (echo machine_info_migration_centre.py not found)

    - name: Run Scripts
      run: |
        python FileFinder_19/file_info_mapfolders.py
        python FileFinder_19/file_info_version_22.py
        python FileFinder_19/machine_info_migration_centre.py

    - name: Run PowerShell Script
      run: pwsh PowerShell/PS__ArunV2_Final_8Feb2024.ps1

    - name: Install PostgreSQL
      run: choco install postgresql

    - name: Run SQL Scripts
      run: |
        psql -f SQLScripts/lisney_files_info8_bp_14Feb2024.sql
        psql -f SQLScripts/sql_Cased_Dimensions14Jan2024_v2.sql
